Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database <init>
INFO: JDBC: jdbc:h2:./database;DB_CLOSE_DELAY=-1
Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.PropertyProvider getProperty
INFO: RulesProperyProvider::getProperty(database_sql):src/main/java/org/hl7/davinci/priorauth/CreateDatabase.sql
Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database <init>
SEVERE: Database::Database:SQLException
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.hl7.davinci.priorauth.Database.getConnection(Database.java:76)
	at org.hl7.davinci.priorauth.Database.<init>(Database.java:89)
	at org.hl7.davinci.priorauth.Database.<init>(Database.java:82)
	at org.hl7.davinci.priorauth.App.initializeAppDB(App.java:58)
	at org.hl7.davinci.priorauth.App.main(App.java:49)
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/vanessuniq/repos/prior-auth/database.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	... 21 more

Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.PropertyProvider getProperty
INFO: RulesProperyProvider::getProperty(CDS_library):CDS-Library/PriorAuth/
Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database write
INFO: Database::write(Rules, { https://bluebutton.cms.gov/resources/codesystem/hcpcsJ7500ImmunosuppressiveDrugsImmunosuppressiveDrugsPriorAuthRule.elm.xml })
Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database write
SEVERE: Database::runQuery:SQLException
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.hl7.davinci.priorauth.Database.getConnection(Database.java:76)
	at org.hl7.davinci.priorauth.Database.write(Database.java:391)
	at org.hl7.davinci.rules.PriorAuthRule.populateRulesTable(PriorAuthRule.java:139)
	at org.hl7.davinci.priorauth.App.initializeAppDB(App.java:59)
	at org.hl7.davinci.priorauth.App.main(App.java:49)
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/vanessuniq/repos/prior-auth/database.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	... 21 more

Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database write
INFO: Database::write(Audit, { null, resource, null, null, Createe2ce20c9-f1ee-41ed-8cb4-94b640c4908e1101008 })
Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database write
SEVERE: Database::runQuery:SQLException
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.hl7.davinci.priorauth.Database.getConnection(Database.java:76)
	at org.hl7.davinci.priorauth.Database.write(Database.java:391)
	at org.hl7.davinci.priorauth.Audit.createAuditEvent(Audit.java:175)
	at org.hl7.davinci.priorauth.Database.write(Database.java:416)
	at org.hl7.davinci.rules.PriorAuthRule.populateRulesTable(PriorAuthRule.java:139)
	at org.hl7.davinci.priorauth.App.initializeAppDB(App.java:59)
	at org.hl7.davinci.priorauth.App.main(App.java:49)
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/vanessuniq/repos/prior-auth/database.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	... 23 more

Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database write
INFO: Database::write(Client, { {"keys":[{"ext":true,"kty":"RSA","e":"AQAB","kid":"3ab8b05b64d799e289e10a201786b38c","key_ops":["verify"],"alg":"RS384","n":"52tcPrGJgzyGqjcUiHsbSk_PxQ7Uovz4saGxva3iyBoidsekonigJJ3LnFlHYb3vBa2NA-0GpX2E1KhNNcYWAWQFcu069zi0YZ_wWGn6PWZURuonUoKH4dGHggym3xxVUxuA8OPubGe5ji56eic4RPINg0z-TtPlS-H9dnDIVznRUTXf3fy2dqWMuTY4D2e4fXGII6OpFAsEyrOqIoR8pLWGu7AiQkothunopp9q_Gu2xqB6l8BNulsbiwsQMeRE-9SGfeFpyblHiizHDwSqeZ3iv49Ellk4yjmrf6wOaFA2IXRqL1cCLj86B6KIDrjdzOL4lOSiES-PclNpioG2rQ"}]}organization, 797da153-9a36-4493-9910-10648a4deb03null, Y3YWq2l08kvFqy50fQJY })
Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database write
SEVERE: Database::runQuery:SQLException
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.hl7.davinci.priorauth.Database.getConnection(Database.java:76)
	at org.hl7.davinci.priorauth.Database.write(Database.java:391)
	at org.hl7.davinci.priorauth.authorization.AuthUtils.populateClientTable(AuthUtils.java:48)
	at org.hl7.davinci.priorauth.App.initializeAppDB(App.java:60)
	at org.hl7.davinci.priorauth.App.main(App.java:49)
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/vanessuniq/repos/prior-auth/database.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	... 21 more

Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database write
INFO: Database::write(Audit, { null, resource, null, null, Create7bd43aa8-b563-40b2-9b63-5f15fd7c771c1101008 })
Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database write
SEVERE: Database::runQuery:SQLException
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.hl7.davinci.priorauth.Database.getConnection(Database.java:76)
	at org.hl7.davinci.priorauth.Database.write(Database.java:391)
	at org.hl7.davinci.priorauth.Audit.createAuditEvent(Audit.java:175)
	at org.hl7.davinci.priorauth.Database.write(Database.java:416)
	at org.hl7.davinci.priorauth.authorization.AuthUtils.populateClientTable(AuthUtils.java:48)
	at org.hl7.davinci.priorauth.App.initializeAppDB(App.java:60)
	at org.hl7.davinci.priorauth.App.main(App.java:49)
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/vanessuniq/repos/prior-auth/database.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	... 23 more

Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database write
INFO: Database::write(Client, { {"keys":[{"kty":"RSA","e":"AQAB","use":"sig","kid":"QjemCvDBrY2NjImHhd2gO9M6ghMW0ZK3R6wcmKGk6NMvgj_H5NZIeCOeopx5brEX","alg":"RS384","n":"iLVJtm0Tb6-S5qomxnmwxaHtWPLMu0K3lLCIwz_7KLKgEsbN0FUaHU0SivGsztD9LRsQ72QtBuyA9LxmK5m_50Lx7hbfUxUPR9rzdj8sz3isiSzryDFm0jq3LsjSu27duiGU0c2oxqpqiC5LWJcW6JcRbtHwnMkU2T0_mdwLLFcdv8ZCxY8ce4vG4E4V3kUmiOYGClkP3eeHiMdXJQ_r4SFwXAuH-uWv_YtkAFE3ChpVlyKsIvXtnncQPoRmf1kPq0obp7veQZvjHIzM9A56TfsnSfBBFwx2oxEX0T2zArDKf3FdMgCzoi63WUUiLmRoPIl5lrtzg17GAhzbAR_WzQ"}]}organization, d9dc3d3e-5be5-4882-832b-e74a93c2d01bnull, Y3YWq2l08kvFqy50fQJY })
Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database write
SEVERE: Database::runQuery:SQLException
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.hl7.davinci.priorauth.Database.getConnection(Database.java:76)
	at org.hl7.davinci.priorauth.Database.write(Database.java:391)
	at org.hl7.davinci.priorauth.authorization.AuthUtils.populateClientTable(AuthUtils.java:65)
	at org.hl7.davinci.priorauth.App.initializeAppDB(App.java:60)
	at org.hl7.davinci.priorauth.App.main(App.java:49)
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/vanessuniq/repos/prior-auth/database.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	... 21 more

Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database write
INFO: Database::write(Audit, { null, resource, null, null, Createf1469a9a-0bc4-4422-9f12-6df6b807b1bd1101008 })
Feb 14, 2022 3:26:41 PM org.hl7.davinci.priorauth.Database write
SEVERE: Database::runQuery:SQLException
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.hl7.davinci.priorauth.Database.getConnection(Database.java:76)
	at org.hl7.davinci.priorauth.Database.write(Database.java:391)
	at org.hl7.davinci.priorauth.Audit.createAuditEvent(Audit.java:175)
	at org.hl7.davinci.priorauth.Database.write(Database.java:416)
	at org.hl7.davinci.priorauth.authorization.AuthUtils.populateClientTable(AuthUtils.java:65)
	at org.hl7.davinci.priorauth.App.initializeAppDB(App.java:60)
	at org.hl7.davinci.priorauth.App.main(App.java:49)
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/vanessuniq/repos/prior-auth/database.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	... 23 more

